CarRentalAgency/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CarRentalAgency.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Rental Location")]
        public string Location { get; set; }
        [Display(Name = "Drop off")]
        public string Destination { get; set; }
        [Required]
        [Display(Name = "Pick-up Date:")]
        public DateTime StarTime { get; set; }
        [Required]
        [Display(Name = "Drop off Date:")]
        public DateTime EndTime { get; set; }
        public DateTime DealTime { get; set; }
        [Display(Name = "Total Price")]
        public int TotalPrice { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        [ForeignKey("Car")]
        public int CarId { get; set; }
        public Car Car { get; set; }
    }
}

CarRentalAgency/Models/OrderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CarRentalAgency.Models
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Rental Location")]
        public string Location { get; set; }
        [Display(Name = "Drop off")]
        public string Destination { get; set; }
        [Required]
        [Display(Name = "Pick-up Date:")]
        public DateTime StarTime { get; set; }
        [Required]
        [Display(Name = "Drop off Date:")]
        public DateTime EndTime { get; set; }
        public DateTime DealTime { get; set; }
        [Display(Name = "Total Price")]
        public int TotalPrice { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public int CarId { get; set; }
        public Car Car { get; set; }
    }
}

CarRentalAgency/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CarRentalAgency.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace CarRentalAgency.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        [Authorize]
        public ActionResult Index(string sortDir, string searchInput, string currentFilter, int? page, string sortOrder = "")
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var orders = db.Orders.AsQueryable();
            if (!User.IsInRole(RoleName.CanManage))
            {
                string userId = User.Identity.GetUserId().ToLower();
                orders = orders.Where(o => o.UserId.ToLower().Contains(userId));
            }
            orders = orders.OrderBy(o => o.Id);

            int pageSize = 5;
            int pageNumber = page ?? 1;
            string para = Request.QueryString["page"];
            if (string.IsNullOrEmpty(para) && string.IsNullOrEmpty(searchInput) && string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(sortDir))
            {
                var data1 = orders.ToPagedList(pageNumber, pageSize);

                return this.View(data1);
            }

            if (!string.IsNullOrEmpty(searchInput))
                orders = orders.Where(o => (o.Location.ToLower().Contains(searchInput.ToLower()) || o.Destination.ToLower().Contains(searchInput.ToLower()) || o.UserName.ToLower().Contains(searchInput.ToLower())));

            switch (sortOrder.ToLower())
            {
                case "id":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Id);
                    else
                        orders = orders.OrderBy(o => o.Id);
                    break;
                case "location":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Location);
                    else
                        orders = orders.OrderBy(o => o.Location);
                    break;
                case "destination":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Destination);
                    else
                        orders = orders.OrderBy(o => o.Destination);
                    break;
                case "startime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.StarTime);
                    else
                        orders = orders.OrderBy(o => o.StarTime);
                    break;
                case "endtime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.EndTime);
                    else
                        orders = orders.OrderBy(o => o.EndTime);
                    break;
                case "dealtime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.DealTime);
                    else
                        orders = orders.OrderBy(o => o.DealTime);
                    break;
                case "totalprice":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.TotalPrice);
                    else
                        orders = orders.OrderBy(o => o.TotalPrice);
                    break;
                case "username":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.UserName);
                    else
                        orders = orders.OrderBy(o => o.UserName);
                    break;
                case "carid":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.CarId);
                    else
                        orders = orders.OrderBy(o => o.CarId);
                    break;
                default:
                    orders = orders.OrderBy(o => o.Id);
                    break;
            }

            var result = orders.ToPagedList(pageNumber, pageSize);
            return PartialView("_OrderView", result);
        }

        [Authorize]
        public ActionResult Search(string sortDir, string searchInput, string currentFilter, int? page, OrderViewModel orderVm, string sortOrder = "")
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var orders = db.Orders.AsQueryable();
            if (!User.IsInRole(RoleName.CanManage))
            {
                string userId = User.Identity.GetUserId().ToLower();
                orders = orders.Where(o => o.UserId.ToLower().Contains(userId));
            }
            orders = orders.OrderBy(o => o.Id);

            int pageSize = 5;
            int pageNumber = page ?? 1;

            if (!string.IsNullOrEmpty(searchInput))
                orders = orders.Where(o => (o.Location.ToLower().Contains(searchInput.ToLower()) || o.Destination.ToLower().Contains(searchInput.ToLower()) || o.UserName.ToLower().Contains(searchInput.ToLower())));

            switch (sortOrder.ToLower())
            {
                case "id":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Id);
                    else
                        orders = orders.OrderBy(o => o.Id);
                    break;
                case "location":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Location);
                    else
                        orders = orders.OrderBy(o => o.Location);
                    break;
                case "destination":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.Destination);
                    else
                        orders = orders.OrderBy(o => o.Destination);
                    break;
                case "startime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.StarTime);
                    else
                        orders = orders.OrderBy(o => o.StarTime);
                    break;
                case "endtime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.EndTime);
                    else
                        orders = orders.OrderBy(o => o.EndTime);
                    break;
                case "dealtime":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.DealTime);
                    else
                        orders = orders.OrderBy(o => o.DealTime);
                    break;
                case "totalprice":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.TotalPrice);
                    else
                        orders = orders.OrderBy(o => o.TotalPrice);
                    break;
                case "username":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.UserName);
                    else
                        orders = orders.OrderBy(o => o.UserName);
                    break;
                case "carid":
                    if (sortDir.ToLower() == "desc")
                        orders = orders.OrderByDescending(o => o.CarId);
                    else
                        orders = orders.OrderBy(o => o.CarId);
                    break;
                default:
                    orders = orders.OrderBy(o => o.Id);
                    break;
            }

            var result = orders.ToPagedList(pageNumber, pageSize);
            return PartialView("_OrderView", result);
        }

        // GET: Orders/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            order.Car = db.Cars.Find(order.CarId);
            if (order?.Car == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Confirmation/5
        [Authorize]
        public ActionResult Confirmation()
        {
            return View();
        }

        // GET: Orders/Create
        [Authorize]
        public ActionResult Create(int? carId)
        {
            if (carId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(carId);
            if (car == null)
            {
                return HttpNotFound();
            }

            OrderViewModel orderVm = new OrderViewModel();
            orderVm.Car = car;
            orderVm.StarTime = DateTime.Now.AddDays(1);
            orderVm.EndTime = DateTime.Now.AddDays(3);
            return View(orderVm);
        }

        // POST: Orders/Create

CarRentalAgency/Views/Orders/Confirmation.cshtml
@{
    ViewBag.Title = "Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation</h2>

<p>Thank you for the reservation. Your Order has been confirmed.</p>

CarRentalAgency/Views/Orders/Create.cshtml
@using CarRentalAgency.Helper
@using CarRentalAgency.Models
@model CarRentalAgency.Models.OrderViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Orders", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <td>
                <div class="form-horizontal" style="background-color: gold">
                    <h4 align="center">Order</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.CarId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StarTime, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.StarTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StarTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" style="background-color: yellowgreen" />
                        </div>
                    </div>
                </div>
            </td>
            <td class="col-md-6">
                <div class="form-horizontal table-bordered" style="background-color: paleturquoise">
                    <h4 align="center">Selected Car</h4>
                    <hr />
                    <dl class="dl-horizontal text-center">
                        <dt>
                            
                        </dt>
                        <dd>
                            @if (Model.Car.Photo != null)
                            {
                                @Html.GetThumbnail(Model.Car.Photo,150,150)
                            }
                        </dd>
                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.Name)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.Seats)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.Seats)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.LargeBagNum)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.LargeBagNum)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.SmallBagNum)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.SmallBagNum)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.SizeId)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.SizeId)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.Rated)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.Rated)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.PricePerDay)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.PricePerDay)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.AirConditioning)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.AirConditioning)
                        </dd>

                        <dt style="width:250px">
                            @Html.DisplayNameFor(model => model.Car.AutomaticTransmission)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Car.AutomaticTransmission)
                        </dd>
                    </dl>
                </div>
            </td>
        </tr>
    </table>
}
@if (User.IsInRole(RoleName.CanManage))
{
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalAgency/Views/Orders/Delete.cshtml
@model CarRentalAgency.Models.Order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StarTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StarTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarRentalAgency/Views/Orders/Details.cshtml
@using CarRentalAgency.Helper
@using CarRentalAgency.Models
@model CarRentalAgency.Models.Order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CarId)

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StarTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StarTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt>

        </dt>
        <dd>
            @if (Model.Car.Photo != null)
            {
                @Html.GetThumbnail(Model.Car.Photo)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Car.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.Seats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Seats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.LargeBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.LargeBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.SmallBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.SmallBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.SizeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.SizeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.Rated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Rated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.AirConditioning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.AirConditioning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.AutomaticTransmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.AutomaticTransmission)
        </dd>
    </dl>
</div>
@if (User.IsInRole(RoleName.CanManage))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CarRentalAgency/Views/Orders/Edit.cshtml
@model CarRentalAgency.Models.Order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.TotalPrice)
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.UserName)
    @Html.HiddenFor(model => model.DealTime)

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StarTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StarTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StarTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayTextFor(model => model.TotalPrice)
            @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DealTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayTextFor(model => model.DealTime)
            @Html.ValidationMessageFor(model => model.DealTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CarId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CarId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CarId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalAgency/Views/Orders/Index.cshtml
@model PagedList.IPagedList<CarRentalAgency.Models.Order>

@{
    ViewBag.Title = "Order List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Order List</h2>

@using (Ajax.BeginForm("Search", "Orders",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "grid",
        InsertionMode = InsertionMode.Replace
    }))
{
    <input type="text" name="searchInput" placeholder="Live Search"
           oninput="$('#searchForm').submit()" value="@ViewBag.CurrentFilter" />
    <input type="submit" value="Search" />

}
<div id="grid">
    @Html.Partial("_OrderView", Model)
</div>