CarRentalAgency/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRentalAgency.Models
{
    public class Car
    {
        [Key]
        public int CarId { get; set; }
        [StringLength(100)]
        [Required]
        public string Name { get; set; }
        [Required]
        public int Seats { get; set; }
        [Required]
        [Display(Name = "large bags number")]
        public int LargeBagNum { get; set; }
        [Display(Name = "Small bags number")]
        public int SmallBagNum { get; set; }
        [Required]
        public Size SizeId { get; set; }
        [Required]
        public double Rated { get; set; }
        public byte[] Photo { get; set; }
        [Required]
        [Display(Name = "Price/day")]
        public int PricePerDay { get; set; }
        [Required]
        [Display(Name = "Air Conditioning")]
        public Boolean AirConditioning { get; set; }
        [Required]
        [Display(Name = "Automatic Transmission")]
        public Boolean AutomaticTransmission { get; set; }
        public Boolean Available { get; set; }
        public enum Size
        {
            Compact,
            Economy,
            FullSize,
            Intermediate,
            Luxury,
            Premium,
            Special,
            Standard
        }
    }
}

CarRentalAgency/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRentalAgency.Models
{
    public class CarViewModel
    {
        [Key]
        public int CarId { get; set; }
        [StringLength(100)]
        [Required]
        public string Name { get; set; }
        [Required]
        public int Seats { get; set; }
        [Required]
        [Display(Name = "large bags number")]
        public int LargeBagNum { get; set; }
        [Display(Name = "Small bags number")]
        public int SmallBagNum { get; set; }
        [Required]
        public Size SizeId { get; set; }
        [Required]
        public double Rated { get; set; }
        [Display(Name = "Photo")]
        public byte[] PhotoDB { get; set; }
        public HttpPostedFileBase Photo { get; set; }
        [Required]
        [Display(Name = "Price/day")]
        public int PricePerDay { get; set; }
        [Required]
        [Display(Name = "Air Conditioning")]
        public Boolean AirConditioning { get; set; }
        [Required]
        [Display(Name = "Automatic Transmission")]
        public Boolean AutomaticTransmission { get; set; }
        public Boolean Available { get; set; }
        public enum Size
        {
            Compact,
            Economy,
            FullSize,
            Intermediate,
            Luxury,
            Premium,
            Special,
            Standard
        }
    }
}

CarRentalAgency/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CarRentalAgency.Helper;
using CarRentalAgency.Models;
using PagedList;

namespace CarRentalAgency.Controllers
{
    public class CarsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cars
        public ActionResult Index(string sortDir, string searchInput, string currentFilter, int? page, string sortOrder = "")
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var cars = db.Cars.AsQueryable();
            cars = cars.OrderBy(c => c.PricePerDay);
            if (!User.IsInRole(RoleName.CanManage))
            {
                cars = cars.Where(c => c.Available == true);
            }
            int pageSize = 5;
            int pageNumber = page ?? 1;
            string para = Request.QueryString["page"];
            if (string.IsNullOrEmpty(para) && string.IsNullOrEmpty(searchInput) && string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(sortDir))
            {
                var data1 = cars.ToPagedList(pageNumber, pageSize);

                //is checking the loginned user
                if (User.IsInRole(RoleName.CanManage))
                    return this.View(data1);
                else
                    return this.View("ReadOnly", data1);
            }

            if (!string.IsNullOrEmpty(searchInput))
                cars = cars.Where(c => c.Name.ToLower().Contains(searchInput.ToLower()));

            switch (sortOrder.ToLower())
            {
                case "name":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.Name);
                    else
                        cars = cars.OrderBy(c => c.Name);
                    break;
                case "seats":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.Seats);
                    else
                        cars = cars.OrderBy(c => c.Seats);
                    break;
                case "largebagnum":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.LargeBagNum);
                    else
                        cars = cars.OrderBy(c => c.LargeBagNum);
                    break;
                case "smallbagnum":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.SmallBagNum);
                    else
                        cars = cars.OrderBy(c => c.SmallBagNum);
                    break;
                case "sizeid":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.SizeId);
                    else
                        cars = cars.OrderBy(c => c.SizeId);
                    break;
                case "rated":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.Rated);
                    else
                        cars = cars.OrderBy(c => c.Rated);
                    break;
                case "priceperday":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.PricePerDay);
                    else
                        cars = cars.OrderBy(c => c.PricePerDay);
                    break;
                case "airconditioning":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.AirConditioning);
                    else
                        cars = cars.OrderBy(c => c.AirConditioning);
                    break;
                case "automatictransmission":
                    if (sortDir.ToLower() == "desc")
                        cars = cars.OrderByDescending(c => c.AutomaticTransmission);
                    else
                        cars = cars.OrderBy(c => c.AutomaticTransmission);
                    break;
                default:
                    cars = cars.OrderBy(c => c.PricePerDay);
                    break;
            }

            var data = cars.ToPagedList(pageNumber, pageSize);

            if (User.IsInRole(RoleName.CanManage))
                return this.PartialView("_CarView", data);
            else
                return this.PartialView("_CarViewReadOnly", data);
        }

        public ActionResult Search(string sortDir, string searchInput, string currentFilter, int? page, OrderViewModel orderVm, string sortOrder = "")
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var result = db.Cars.AsQueryable();
            result = result.OrderBy(c => c.PricePerDay);
            if (!User.IsInRole(RoleName.CanManage))
            {
                result = result.Where(c => c.Available == true);
            }
            if (!string.IsNullOrEmpty(searchInput))
                result = result.Where(c => c.Name.ToLower().Contains(searchInput.ToLower()));

            int pageSize = 5;
            int pageNumber = page ?? 1;

            switch (sortOrder.ToLower())
            {
                case "name":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.Name);
                    else
                        result = result.OrderBy(c => c.Name);
                    break;
                case "seats":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.Seats);
                    else
                        result = result.OrderBy(c => c.Seats);
                    break;
                case "largebagnum":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.LargeBagNum);
                    else
                        result = result.OrderBy(c => c.LargeBagNum);
                    break;
                case "smallbagnum":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.SmallBagNum);
                    else
                        result = result.OrderBy(c => c.SmallBagNum);
                    break;
                case "sizeid":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.SizeId);
                    else
                        result = result.OrderBy(c => c.SizeId);
                    break;
                case "rated":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.Rated);
                    else
                        result = result.OrderBy(c => c.Rated);
                    break;
                case "priceperday":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.PricePerDay);
                    else
                        result = result.OrderBy(c => c.PricePerDay);
                    break;
                case "airconditioning":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.AirConditioning);
                    else
                        result = result.OrderBy(c => c.AirConditioning);
                    break;
                case "automatictransmission":
                    if (sortDir.ToLower() == "desc")
                        result = result.OrderByDescending(c => c.AutomaticTransmission);
                    else
                        result = result.OrderBy(c => c.AutomaticTransmission);
                    break;
                default:
                    result = result.OrderBy(c => c.PricePerDay);
                    break;
            }

            var data = result.ToPagedList(pageNumber, pageSize);
            if (User.IsInRole(RoleName.CanManage))
                return this.PartialView("_CarView", data);
            else
                return this.PartialView("_CarViewReadOnly", data);
        }

        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }
        [Authorize(Roles = RoleName.CanManage)]
        // GET: Cars/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Create([Bind(Include = "CarId,Name,Seats,LargeBagNum,SmallBagNum,SizeId,Rated,Photo,PhotoDB,PricePerDay,AirConditioning,AutomaticTransmission,Available")] CarViewModel carVm)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<CarViewModel, Car>().ForMember(c => c.Photo, opt => opt.Ignore());

CarRentalAgency/Views/Cars/Create.cshtml
@using CarRentalAgency.Helper
@using CarRentalAgency.Models
@model CarRentalAgency.Models.CarViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Cars", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LargeBagNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LargeBagNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LargeBagNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmallBagNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmallBagNum, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.SmallBagNum, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.SizeId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
                @if (Model != null && Model.PhotoDB != null)
                {
                    @Html.GetThumbnail(Model.PhotoDB, 150, 150)
                }
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AirConditioning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AirConditioning)
                    @Html.ValidationMessageFor(model => model.AirConditioning, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutomaticTransmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AutomaticTransmission)
                    @Html.ValidationMessageFor(model => model.AutomaticTransmission, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalAgency/Views/Cars/Delete.cshtml
@using CarRentalAgency.Helper
@model CarRentalAgency.Models.Car

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LargeBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LargeBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmallBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmallBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SizeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SizeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rated)
        </dd>

        <dt>
            @if (Model.Photo != null)
            {
                @Html.GetThumbnail(Model.Photo)
            }
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AirConditioning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AirConditioning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AutomaticTransmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutomaticTransmission)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarRentalAgency/Views/Cars/Details.cshtml
@using CarRentalAgency.Helper
@using CarRentalAgency.Models
@model CarRentalAgency.Models.Car

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LargeBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LargeBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SmallBagNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmallBagNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SizeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SizeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.Photo != null)
            {
                @Html.GetThumbnail(Model.Photo)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AirConditioning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AirConditioning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AutomaticTransmission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutomaticTransmission)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>
</div>

<p>
@if (User.IsInRole(RoleName.CanManage)) { 
    @Html.ActionLink("Edit", "Edit", new {id = Model.CarId}) |
}
    @Html.ActionLink("Back to List", "Index")
</p>

CarRentalAgency/Views/Cars/Edit.cshtml
@using CarRentalAgency.Helper
@model CarRentalAgency.Models.CarViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Cars", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LargeBagNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LargeBagNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LargeBagNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmallBagNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmallBagNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SmallBagNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.SizeId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.HiddenFor(model => model.PhotoDB)
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                @if (Model != null && Model.PhotoDB != null)
                {
                    @Html.GetThumbnail(Model.PhotoDB, 150, 150)
                }
                @Html.ValidationMessageFor(model => model.PhotoDB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AirConditioning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AirConditioning)
                    @Html.ValidationMessageFor(model => model.AirConditioning, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutomaticTransmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AutomaticTransmission)
                    @Html.ValidationMessageFor(model => model.AutomaticTransmission, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalAgency/Views/Cars/Index.cshtml
@model PagedList.IPagedList<CarRentalAgency.Models.Car>

@{
    ViewBag.Title = "Car List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Car List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Ajax.BeginForm("Search", "Cars",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "results",
        InsertionMode = InsertionMode.Replace
    }))
{
    <input type="text" name="searchInput" placeholder="Live Search"
           oninput="$('#searchForm').submit()" value="@ViewBag.CurrentFilter" />
    <input type="submit" value="Search" />
    
}
<div id="results">
    @Html.Partial("_CarView", Model)
</div>

CarRentalAgency/Views/Cars/ReadOnly.cshtml
@using CarRentalAgency.Helper
@model PagedList.IPagedList<CarRentalAgency.Models.Car>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Car List</h2>
@using (Ajax.BeginForm("Search", "Cars",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "results",
        InsertionMode = InsertionMode.Replace
    }))
{
    <input type="text" name="searchInput" placeholder="Live Search"
           oninput="$('#searchForm').submit()" value="@ViewBag.CurrentFilter" />
    <input type="submit" value="Search" />
}
<div id="results">
    @Html.Partial("_CarViewReadOnly", Model)
</div>